-- 코드를 작성해주세요
SELECT t2.ID
FROM ECOLI_DATA t1
INNER JOIN ECOLI_DATA t2 ON t1.ID = t2.PARENT_ID
WHERE t1.ID IN (SELECT t4.ID
                FROM ECOLI_DATA t3
                INNER JOIN ECOLI_DATA t4 ON t3.ID = t4.PARENT_ID
                WHERE t3.PARENT_ID IS NULL)
ORDER BY t2.ID
