
SELECT i.CAR_ID
        , i.CAR_TYPE
        , ROUND(i.DAILY_FEE * (100 - d.discount_rate) * 0.01 * 30) as FEE
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_ID NOT IN (SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
        AND CAR_TYPE IN ('세단', 'SUV')) i
JOIN (SELECT *
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
        WHERE DURATION_TYPE = '30일 이상') d
ON i.CAR_TYPE = d.CAR_TYPE
WHERE ROUND(i.DAILY_FEE * (100 - d.discount_rate) * 0.01 * 30) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC

