-- 코드를 작성해주세요
SELECT t2.ID, t2.GENOTYPE, t1.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA t1
INNER JOIN ECOLI_DATA t2 ON t1.ID = t2.PARENT_ID
WHERE (t1.GENOTYPE & t2.GENOTYPE) = t1.GENOTYPE
ORDER BY ID ASC