

SELECT a.ID, c.FISH_NAME, a.LENGTH
FROM FISH_INFO a
NATURAL JOIN (SELECT FISH_TYPE, MAX(LENGTH) LENGTH
            FROM FISH_INFO 
            GROUP BY FISH_TYPE) b
NATURAL JOIN FISH_NAME_INFO c   
WHERE a.LENGTH = b.LENGTH
ORDER BY ID ASC